intro_bot= input("hi you will be using thing calcater and to say 0 times 0 is just 0 and 0 devied by 0= undifned and 0 minus 0 is 0 and 0 plus 0 is 0 the calatters may or may not be able to do that so thats why i am saying it now and any thing thats has 0 and 0 b its self will be most liekly 0 but if its devition it would not be 0 and read and folow the directions and do so and it will start with first the adishtion then subtraction then mulipication then devshtion then same order but this time with rounder bots but same order then after that there is a small encyclopedia ")
print(intro_bot)
adishtion_bot= input("hi i am your aidshtion math bot that can help with math and to do adishtion you add them such as like 2 ice creams plus more would 4 butcause you had then you added 2 more giving you 4 as that was a example on how to do it")
number1= float(input("first number for problom"))
print(number1)
number2= float(input("second number for problom"))
print(number2)
answer= (number1 + number2)
print(answer)
subtraction_bot= input("hi i am your aidshtion math bot that can help with math and to do subtraction and to do subtraction you subtract them such as like 2 ice creams then you subtract 2 you would have 0 butcause you subtracted them thats a example on how to do them")
number3= float(input("first number for problom"))
print(number3)
number4= float(input("second number for problom"))
print(number4)
answer= (number3 - number4)
print(answer)
mutltiplucation_bot= input("hi i am your multiplacation math bot that can help with math and to do multiplaication and to do multiplaication it means to multiply them if you have 2 and 2 and you multiply them you would get 4 or like 5 and 2 and multiply them you get 10 because you multiplided")
number5= float(input("first number for problom"))
print(number5)
number6= float(input("second number for problom"))
print(number6)
answer= (number5 * number6)
print(answer)
devistion_bot= input("hi i am your devtion math bot that can help with math and to do devtion you devie so like if you have 4 and you devie the number by 2 it would be 2 because 4 devied by 2 is 2 because you devied and 0 devied by 0= undfined")
number7= float(input("first number for problom"))
print(number7)
number8= float(input("second number for problom"))
print(number8)
answer= (number7 / number8)
print(answer)
adishtion_bot_rounder_bot= input("now im you rounder bot for adistion sice you know adishtion or have been explained roundering is where you estimate such as you have to folow the rule anything that is 5 and above rounds up and anything 4 and bellow rounds down but this bot does it for you")
number9= round(float(input("first number for problom")))
print(number9)
number10= round(float(input("second number for problom")))
print(number10)
answer= (number9 + number10)
print(answer)
subtraction_bot_rounder_bot= input("now im you rounder bot for subtraction sice you know subtraction or have been explained roundering is where you estimate such as you have to folow the rule anything that is 5 and above rounds up and anything 4 and bellow rounds down but this bot does it for you")
number11= round(float(input("first number for problom")))
print(number11)
number12= round(float(input("second number for problom")))
print(number12)
answer= (number11 - number12)
print(answer)
multiplicatio_bot_rounder_bot= input("now im you rounder bot for multiplication sice you know multiplication or have been explained roundering is where you estimate such as you have to folow the rule anything that is 5 and above rounds up and anything 4 and bellow rounds down but this bot does it for you")
number13= round(float(input("first number for problom")))
print(number13)
number14= round(float(input("second number for problom")))
print(number14)
answer= (number13 * number14)
print(answer)
devistion_bot_rounder_bot= input("now im you rounder bot for devition sice you know devtion or have been explained roundering is where you estimate such as you have to folow the rule anything that is 5 and above rounds up and anything 4 and bellow rounds down but thisbot does it for you")
number15= round(float(input("first number for problom")))
print(number15)
number16= round(float(input("second number for problom")))
print(number16)
answer= (number15 / number16)
print(answer)
ending_bot= input("you have used the program  thanks for using the program but we also don't just offer math but a small encyclopedia")
print(ending_bot)
bot_smarts= ("first article in the encyclopedia.")
print(bot_smarts)
botvolume1= bot_volume1= input("volume 1 first article the five whys to give some background knowledge on the five whys the five whys is used for cause and effect realation ships and is used for problems such as, example bolts are cross threading in the gine block on the production line. first why-the threads aren't cut cleanly. now the first wy is the first part of the analysis now the first part of the analysis should lead to the second part of analysis such as the second why- The cutting tool on the lathe wasn't changed at all today. that first part of analysis lead up to analysis two and analysis two should lead up analysis three which now the second why- the replacement cutting tool bin was empty now that the third pice of the analysis now the third pice should lead up to the 4th pice of analysis here is the 4th pecie of analysis. why-the bin's contents had fallen and rolled under the shelves. now the third part of analysis lead up to the 4th [art now the 5th part says the issue that lead to all of these events so the 5th pice the final part is why- one of the feet on the shelves has rusted and failed, making the shelves unstable, and when it was jostled, many parts fell on the floor including the lost cutting tools. now the five why is supposed to determine the root cause. but some will say that the five whys is insufficent because its just five and ther argument for why the five whys is not sufficeint is because first it lacks depth but now why well because the problum may or may be deeper than just that and some will also make a argument that it is not deep enuff shuch as it only hits the surface the question because it stops at 5 when their could be 10 whys maybe and some say it lacks complexey because it hits the surface. now to toal up what their saying is as a summery is the five whys lacks depth,complexdy and that their is not anuff why. but to make the five why better is keep asking why intill find the root of the cause not 5 but intil you fined the root cause")
print(bot_volume1)
bot2volume1= input("volume 1 second article when we study italy we need to ook at grapes such as g=geograhy,r=religion,a=achevments,p=palltics,s=social system. so accoding to Britannica it is located in souther Europe and now we look at their religion most of them are consiterd roman catholics and with a estumated amount is about 71% to 79% so thats the main religion and now their soical system or how there social strucure work there upper class is the Bourgeoisie thast the upper class and only about 10% are that class and under that we have the White-Collar Middle Class: Approximately 17%, including office employees and non-manual workers. now we have the Urban/Rural Petite Bourgeoisie: Roughly 17% (urban) to 10% (rural), consisting of small business owners, artisans, and shopkeepers. and now we have the lower class and this class is the Urban Working Class: The largest group at 37%, comprising manual laborers in cities. and now we have the lowest class the Rural Working Class: Roughly 9%, consisting of agricultural laborers. but primarily categorized by economic status, moving from an upper-class bourgeoisie to a large,now we have the there poltics here is there poltics diverse working class Executive Branch: The Prime Minister (President of the Council of Ministers) acts as the head of government, appointed by the President of the Republic and requiring confidence from both houses of Parliament and we there and now we have the Legislative Branch: A symmetric bicameral parliament, consisting of the Chamber of Deputies (400 members) and the Senate (200 members), both directly elected for five-year terms. Both houses have equal power and must approve legislation. and also now we have Electoral System: A mixed system combines proportional representation (roughly 63–75% of seats) with first-past-the-post (roughly 25–37% of seats).and now we have the Head of State: The President is elected for a seven-year term by parliament and regional delegates. and now we have the Political Instability: Italy often experiences short-lived coalition governments due to fragmented, multi-party competition and now we have their achievements and their achievements are really aming lets do a deep dive here is their achievements he Renaissance, the invention of the piano, battery, and thermometer, foundational Roman law, and shaping modern fashion, cuisine, and design. and the people of italy speak Italian")
print(bot2volume1)